services:
  - type: web
    name: hospital-finder
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/browser
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
