name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create environment files
        run: |
          echo 'export const environment = {
            production: true,
            apiUrl: "https://www.preggifyapiservice.preggify.com/preggify/v1/"
          };' > src/environments/environment.prod.ts
          
          echo 'export const environment = {
            production: false,
            apiUrl: "https://www.preggifyapiservice.preggify.com/preggify/v1/"
          };' > src/environments/environment.ts

      - name: Build
        run: npm run build -- --base-href="https://preggify.github.io/Hospital_finder/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/browser
